language: node_js
node_js:
- '6'
install:
  - npm install -g codecov nyc mocha
  - cd $TRAVIS_BUILD_DIR/server
  - npm install
  - cd $TRAVIS_BUILD_DIR/client
  - npm install
script:
  - cd $TRAVIS_BUILD_DIR/server
  - npm test
  - rm database_test.sqlite
  - npm run coverage
  - codecov
  - rm database_test.sqlite
  - cd $TRAVIS_BUILD_DIR/client
  - npm build
env:
  matrix:
  global:
    - TZ=America/New_York
